import type {Caption} from '@remotion/captions';

export type GuidedCaption = Caption & {
  highlight?: string;
};

export const slideCaptions: GuidedCaption[][] = [
  [
    {
      text: 'AI에게 묻는 단계에서, 일을 맡기는 단계로 이동합니다.',
      highlight: '일을 맡기는',
      startMs: 900,
      endMs: 9000,
      timestampMs: null,
      confidence: null,
    },
    {
      text: 'Assistant는 답변을 주고, Agent는 결과물을 만듭니다.',
      highlight: '결과물',
      startMs: 9000,
      endMs: 21000,
      timestampMs: null,
      confidence: null,
    },
    {
      text: '오늘 목표는 업무 하나를 실제 파일로 받아보는 것입니다.',
      highlight: '실제 파일',
      startMs: 21000,
      endMs: 29500,
      timestampMs: null,
      confidence: null,
    },
  ],
  [
    {
      text: '처음부터 큰 자동화를 만들 필요는 없습니다.',
      highlight: '큰 자동화',
      startMs: 700,
      endMs: 6500,
      timestampMs: null,
      confidence: null,
    },
    {
      text: '자료 하나, 산출물 하나, 검토 한 번이면 충분합니다.',
      highlight: '검토',
      startMs: 6500,
      endMs: 18500,
      timestampMs: null,
      confidence: null,
    },
    {
      text: '작은 성공을 다음 업무의 프롬프트로 저장합니다.',
      highlight: '작은 성공',
      startMs: 18500,
      endMs: 26500,
      timestampMs: null,
      confidence: null,
    },
  ],
  [
    {
      text: 'Assistant는 옆에서 돕는 역할입니다.',
      highlight: '돕는',
      startMs: 800,
      endMs: 8000,
      timestampMs: null,
      confidence: null,
    },
    {
      text: 'Agent는 사용자가 하던 실행 과정을 대신 수행합니다.',
      highlight: '대신 수행',
      startMs: 8000,
      endMs: 19000,
      timestampMs: null,
      confidence: null,
    },
    {
      text: 'Codex는 답변보다 산출물에 가까운 도구입니다.',
      highlight: '산출물',
      startMs: 19000,
      endMs: 26500,
      timestampMs: null,
      confidence: null,
    },
  ],
  [
    {
      text: 'ChatGPT는 모르는 업무를 빠르게 이해하게 해줍니다.',
      highlight: '빠르게 이해',
      startMs: 800,
      endMs: 8000,
      timestampMs: null,
      confidence: null,
    },
    {
      text: '원리, 예시, 실수까지 한 번에 기준으로 정리합니다.',
      highlight: '기준',
      startMs: 8000,
      endMs: 19000,
      timestampMs: null,
      confidence: null,
    },
    {
      text: '이 단계의 목적은 내가 더 잘 판단하게 되는 것입니다.',
      highlight: '판단',
      startMs: 19000,
      endMs: 26500,
      timestampMs: null,
      confidence: null,
    },
  ],
  [
    {
      text: '좋은 답변을 받아도 일이 끝난 것은 아닙니다.',
      highlight: '끝난 것',
      startMs: 800,
      endMs: 7500,
      timestampMs: null,
      confidence: null,
    },
    {
      text: '복사, 실행, 저장은 여전히 사람의 손에 남습니다.',
      highlight: '사람의 손',
      startMs: 7500,
      endMs: 19000,
      timestampMs: null,
      confidence: null,
    },
    {
      text: '반복되는 실행 과정을 Codex에게 넘길 준비를 합니다.',
      highlight: 'Codex',
      startMs: 19000,
      endMs: 27500,
      timestampMs: null,
      confidence: null,
    },
  ],
  [
    {
      text: '실습은 모두가 같은 출발선에서 시작해야 합니다.',
      highlight: '같은 출발선',
      startMs: 800,
      endMs: 7500,
      timestampMs: null,
      confidence: null,
    },
    {
      text: 'ZIP을 풀고 HTML 가이드로 전체 흐름을 확인합니다.',
      highlight: 'HTML 가이드',
      startMs: 7500,
      endMs: 17500,
      timestampMs: null,
      confidence: null,
    },
    {
      text: '그다음 Codex에서 프로젝트 폴더를 지정합니다.',
      highlight: '프로젝트 폴더',
      startMs: 17500,
      endMs: 25500,
      timestampMs: null,
      confidence: null,
    },
  ],
  [
    {
      text: '인앱 브라우저는 보는 도구에서 실행 도구로 바뀝니다.',
      highlight: '실행 도구',
      startMs: 800,
      endMs: 8000,
      timestampMs: null,
      confidence: null,
    },
    {
      text: '웹페이지의 핵심 내용을 추출하고 정리합니다.',
      highlight: '핵심 내용',
      startMs: 8000,
      endMs: 17000,
      timestampMs: null,
      confidence: null,
    },
    {
      text: '마지막에는 다음 행동 목록으로 바꿉니다.',
      highlight: '행동 목록',
      startMs: 17000,
      endMs: 25500,
      timestampMs: null,
      confidence: null,
    },
  ],
  [
    {
      text: '컴퓨터 정리는 바로 실행하지 않는 것이 핵심입니다.',
      highlight: '바로 실행하지 않는',
      startMs: 800,
      endMs: 8000,
      timestampMs: null,
      confidence: null,
    },
    {
      text: '먼저 기준을 만들고, 드라이 런으로 후보를 확인합니다.',
      highlight: '드라이 런',
      startMs: 8000,
      endMs: 17500,
      timestampMs: null,
      confidence: null,
    },
    {
      text: '승인 후 실행하는 절차가 안전한 자동화입니다.',
      highlight: '승인 후 실행',
      startMs: 17500,
      endMs: 24500,
      timestampMs: null,
      confidence: null,
    },
  ],
  [
    {
      text: '근무표 이미지는 먼저 사람이 보듯 확인합니다.',
      highlight: '근무표 이미지',
      startMs: 800,
      endMs: 7500,
      timestampMs: null,
      confidence: null,
    },
    {
      text: '날짜와 근무 코드를 구조화된 표로 추출합니다.',
      highlight: '구조화된 표',
      startMs: 7500,
      endMs: 19000,
      timestampMs: null,
      confidence: null,
    },
    {
      text: '마지막에는 Calendar에 넣을 일정 후보로 바꿉니다.',
      highlight: '일정 후보',
      startMs: 19000,
      endMs: 27500,
      timestampMs: null,
      confidence: null,
    },
  ],
  [
    {
      text: '표 데이터는 그대로 두면 설득력이 약합니다.',
      highlight: '설득력',
      startMs: 800,
      endMs: 7500,
      timestampMs: null,
      confidence: null,
    },
    {
      text: 'CSV를 Excel 분석 파일과 차트로 바꿉니다.',
      highlight: '차트',
      startMs: 7500,
      endMs: 18500,
      timestampMs: null,
      confidence: null,
    },
    {
      text: '숫자를 보고와 강의에 쓸 메시지로 만듭니다.',
      highlight: '메시지',
      startMs: 18500,
      endMs: 26500,
      timestampMs: null,
      confidence: null,
    },
  ],
  [
    {
      text: '긴 환자 안내문은 정확하지만 부담스러울 수 있습니다.',
      highlight: '부담',
      startMs: 800,
      endMs: 8500,
      timestampMs: null,
      confidence: null,
    },
    {
      text: '핵심을 세 문장으로 줄이고 카드 세 장으로 나눕니다.',
      highlight: '카드 세 장',
      startMs: 8500,
      endMs: 19500,
      timestampMs: null,
      confidence: null,
    },
    {
      text: '환자가 준비할 일과 주의할 점에 집중합니다.',
      highlight: '주의할 점',
      startMs: 19500,
      endMs: 27500,
      timestampMs: null,
      confidence: null,
    },
  ],
  [
    {
      text: '논문은 읽는 데서 끝내지 않습니다.',
      highlight: '끝내지 않습니다',
      startMs: 800,
      endMs: 6500,
      timestampMs: null,
      confidence: null,
    },
    {
      text: '비교표, 학습 노트, 강의 슬라이드로 확장합니다.',
      highlight: '확장',
      startMs: 6500,
      endMs: 18000,
      timestampMs: null,
      confidence: null,
    },
    {
      text: '출처와 한계를 남기면 강의 준비물이 됩니다.',
      highlight: '출처와 한계',
      startMs: 18000,
      endMs: 25500,
      timestampMs: null,
      confidence: null,
    },
  ],
  [
    {
      text: 'Codex 프롬프트는 길이보다 빈칸이 중요합니다.',
      highlight: '빈칸',
      startMs: 800,
      endMs: 7500,
      timestampMs: null,
      confidence: null,
    },
    {
      text: '자료, 작업, 산출물, 제약, 검토를 채웁니다.',
      highlight: '검토',
      startMs: 7500,
      endMs: 18500,
      timestampMs: null,
      confidence: null,
    },
    {
      text: '다섯 칸이 채워지면 바로 업무에 적용할 수 있습니다.',
      highlight: '업무에 적용',
      startMs: 18500,
      endMs: 25500,
      timestampMs: null,
      confidence: null,
    },
  ],
  [
    {
      text: '마지막 과제는 크게 시작하지 않는 것입니다.',
      highlight: '크게 시작하지',
      startMs: 800,
      endMs: 7000,
      timestampMs: null,
      confidence: null,
    },
    {
      text: '오늘 한 가지 업무만 Codex에게 파일로 맡겨보세요.',
      highlight: '한 가지 업무',
      startMs: 7000,
      endMs: 18500,
      timestampMs: null,
      confidence: null,
    },
    {
      text: '결과 파일을 열어 검토하고, 잘 된 프롬프트를 저장합니다.',
      highlight: '프롬프트를 저장',
      startMs: 18500,
      endMs: 26500,
      timestampMs: null,
      confidence: null,
    },
  ],
];
