export type FocusPoint = {
  at: number;
  scale: number;
  x: number;
  y: number;
  label: string;
};

export type SlideSpec = {
  id: number;
  kicker: string;
  title: string;
  asset?: string;
  cards?: string[];
  fit?: 'cover' | 'contain';
  why: string;
  order: string[];
  result: string;
  script: string;
  cta: string;
  focus: FocusPoint[];
  highlight: {x: number; y: number; w: number; h: number};
};

export const slides: SlideSpec[] = [
  {
    id: 1,
    kicker: '제 1강',
    title: 'AI에게 묻기에서, AI에게 맡기기로',
    asset: 'gpt-cover.png',
    fit: 'cover',
    why: '답변이 아니라 완성 파일이 오늘의 기준입니다.',
    order: ['질문하기', '일 맡기기', '결과 검토'],
    result: 'Assistant와 Agent의 차이를 몸으로 이해합니다.',
    script: '오늘 강의의 핵심은 AI에게 답을 얻는 것에서 끝나지 않고, 실제 파일 형태의 결과물을 맡겨보는 것입니다.',
    cta: '답변을 받는 경험에서 결과 파일을 받는 경험으로 이동합니다.',
    focus: [
      {at: 0, scale: 1.05, x: 0, y: 0, label: '전체 맥락'},
      {at: 3, scale: 1.22, x: 210, y: 10, label: '질문과 답변'},
      {at: 7, scale: 1.22, x: -230, y: -10, label: '파일을 만드는 Agent'},
      {at: 11, scale: 1.02, x: 0, y: 0, label: '오늘의 전환'},
    ],
    highlight: {x: 1030, y: 200, w: 520, h: 430},
  },
  {
    id: 2,
    kicker: '오늘의 완성 기준',
    title: '작게 요청하고, 파일로 받으면 실습이 쉬워집니다',
    asset: 'gpt-prompt-formula.png',
    fit: 'cover',
    why: '처음부터 큰 자동화를 만들려고 하면 막힙니다.',
    order: ['작은 자료', '명확한 산출물', '열어 검토'],
    result: '작은 성공이 반복 가능한 프롬프트가 됩니다.',
    script: '작은 자료 하나, 명확한 산출물 하나, 결과 파일 열어보기라는 세 단계만 성공시키면 됩니다.',
    cta: '세 단계만 완성하면 오늘 실습은 성공입니다.',
    focus: [
      {at: 0, scale: 1.04, x: 0, y: 0, label: '전체 공식'},
      {at: 3, scale: 1.28, x: 420, y: 60, label: '작은 자료'},
      {at: 6, scale: 1.28, x: 0, y: 40, label: '산출물 지정'},
      {at: 9, scale: 1.25, x: -420, y: 50, label: '검토와 저장'},
    ],
    highlight: {x: 650, y: 140, w: 620, h: 420},
  },
  {
    id: 3,
    kicker: '핵심 개념',
    title: 'Assistant는 옆에서 돕고, Agent는 대신 수행합니다',
    asset: 'gpt-assistant-agent.png',
    fit: 'cover',
    why: '같은 AI라도 사용자의 관여 수준이 다릅니다.',
    order: ['Assistant: 답변', '사용자: 실행', 'Agent: 결과물'],
    result: 'Codex는 대신 수행하는 쪽에 가깝습니다.',
    script: 'Assistant는 사용자가 질문하면 답을 주고, Agent는 사용자가 해야 할 일을 대신 수행해 결과물까지 도달합니다.',
    cta: 'Codex를 답변기가 아니라 실행 파트너로 봅니다.',
    focus: [
      {at: 0, scale: 1.03, x: 0, y: 0, label: '비교 전체'},
      {at: 3, scale: 1.22, x: 310, y: 0, label: 'Assistant'},
      {at: 7, scale: 1.22, x: -310, y: 0, label: 'Agent'},
      {at: 11, scale: 1.02, x: 0, y: 0, label: '역할 차이'},
    ],
    highlight: {x: 1030, y: 120, w: 570, h: 520},
  },
  {
    id: 4,
    kicker: '제 2강',
    title: 'ChatGPT는 학습과 판단 기준을 빠르게 만들어줍니다',
    asset: 'gpt-chatgpt-learning.png',
    fit: 'cover',
    why: '모르는 업무의 원리와 절차를 빠르게 익힙니다.',
    order: ['개념 질문', '예시 요청', '업무 기준 정리'],
    result: '내가 더 잘 일하게 만드는 조력자입니다.',
    script: 'VLOOKUP 같은 낯선 기능도 개념과 예시, 주의점을 한 번에 얻을 수 있습니다.',
    cta: '모르는 업무는 먼저 학습 가능한 기준으로 바꿉니다.',
    focus: [
      {at: 0, scale: 1.05, x: 0, y: 0, label: '학습 화면'},
      {at: 3, scale: 1.22, x: 350, y: 20, label: '개념 질문'},
      {at: 6, scale: 1.22, x: -40, y: -20, label: '예시와 자료'},
      {at: 9, scale: 1.2, x: -360, y: 10, label: '기준 정리'},
    ],
    highlight: {x: 1000, y: 160, w: 520, h: 380},
  },
  {
    id: 5,
    kicker: '한계 인식',
    title: '답변만으로는 복사, 실행, 저장이 여전히 내 일입니다',
    asset: 'gpt-manual-limit.png',
    fit: 'cover',
    why: '좋은 답변도 산출물로 바꾸는 손작업이 남습니다.',
    order: ['답변 받기', '복사/붙여넣기', '직접 실행'],
    result: '반복 업무에서는 Agent가 필요해집니다.',
    script: '복사하고 붙여넣고 실행하고 저장해야 하는 반복이 많아질수록 Agent가 필요한 이유가 분명해집니다.',
    cta: '반복되는 손작업을 Codex에게 넘길 준비를 합니다.',
    focus: [
      {at: 0, scale: 1.04, x: 0, y: 0, label: '수작업 흐름'},
      {at: 3, scale: 1.22, x: 260, y: 10, label: '답변 받기'},
      {at: 6, scale: 1.24, x: -40, y: 10, label: '복사/실행'},
      {at: 9, scale: 1.23, x: -310, y: 0, label: '저장 병목'},
    ],
    highlight: {x: 850, y: 190, w: 560, h: 380},
  },
  {
    id: 6,
    kicker: '제 3강 시작',
    title: 'ZIP을 풀고 HTML 가이드를 여는 것부터 시작합니다',
    asset: 'gpt-codex-setup.png',
    fit: 'cover',
    why: '설치 장벽을 낮추면 바로 실습으로 들어갑니다.',
    order: ['ZIP 압축 해제', 'HTML 열기', '폴더 지정'],
    result: '모두 같은 실습 화면에서 출발합니다.',
    script: '수강생이 같은 폴더 구조와 같은 샘플 자료를 보게 만드는 것이 강의 운영의 핵심입니다.',
    cta: '같은 출발선을 먼저 만듭니다.',
    focus: [
      {at: 0, scale: 1.04, x: 0, y: 0, label: '세팅 전체'},
      {at: 3, scale: 1.24, x: 430, y: 0, label: 'ZIP'},
      {at: 6, scale: 1.24, x: 0, y: 0, label: 'HTML 가이드'},
      {at: 9, scale: 1.22, x: -420, y: 0, label: '프로젝트 폴더'},
    ],
    highlight: {x: 180, y: 140, w: 500, h: 430},
  },
  {
    id: 7,
    kicker: 'Chapter 1',
    title: '인앱 브라우저는 웹 내용을 읽고 행동 목록으로 바꿉니다',
    asset: 'gpt-browser-briefing.png',
    fit: 'cover',
    why: '웹을 보는 일과 요약하는 일을 분리하지 않습니다.',
    order: ['페이지 열기', '핵심 추출', '다음 행동'],
    result: '공지와 자료가 업무 브리핑으로 바뀝니다.',
    script: '페이지를 열고 핵심 내용을 추출한 뒤 다음 행동 목록으로 바꿉니다.',
    cta: '웹페이지를 행동 가능한 브리핑으로 만듭니다.',
    focus: [
      {at: 0, scale: 1.04, x: 0, y: 0, label: '브라우저 전체'},
      {at: 3, scale: 1.2, x: 360, y: 10, label: '페이지 열기'},
      {at: 6, scale: 1.2, x: -20, y: 0, label: '핵심 추출'},
      {at: 9, scale: 1.2, x: -380, y: 0, label: '행동 목록'},
    ],
    highlight: {x: 1050, y: 180, w: 450, h: 420},
  },
  {
    id: 8,
    kicker: 'Chapter 2',
    title: '컴퓨터 정리는 제안, 검토, 실행 순서로 갑니다',
    asset: 'gpt-file-cleanup.png',
    fit: 'cover',
    why: '삭제와 이동은 안전 절차가 먼저입니다.',
    order: ['정리 기준', 'Dry run', '승인 후 실행'],
    result: '위험한 자동화도 검토 가능한 작업이 됩니다.',
    script: '파일 정리처럼 위험할 수 있는 자동화는 먼저 기준을 만들고 dry run으로 후보를 확인해야 합니다.',
    cta: '자동화보다 검토 가능한 작업이 먼저입니다.',
    focus: [
      {at: 0, scale: 1.04, x: 0, y: 0, label: '정리 전체'},
      {at: 3, scale: 1.2, x: 330, y: 0, label: '후보 파일'},
      {at: 6, scale: 1.24, x: -10, y: -20, label: '안전 검토'},
      {at: 9, scale: 1.22, x: -360, y: 0, label: '승인 실행'},
    ],
    highlight: {x: 760, y: 140, w: 470, h: 440},
  },
  {
    id: 9,
    kicker: 'Chapter 3',
    title: '근무표 이미지는 구조화 표와 Calendar 후보로 바꿉니다',
    asset: 'schedule-original-82_2603.jpeg',
    fit: 'contain',
    why: '이미지는 사람이 읽지만 일정 앱은 구조화 데이터가 필요합니다.',
    order: ['이미지 확인', '근무 코드 추출', 'Calendar 후보'],
    result: '수정 가능한 일정 초안까지 도달합니다.',
    script: '근무표 이미지는 먼저 근무 코드를 추출하고 구조화 표로 바꾼 뒤 Calendar 후보로 정리합니다.',
    cta: '표 이미지를 일정 데이터로 바꿉니다.',
    focus: [
      {at: 0, scale: 1.1, x: 0, y: 0, label: '원본 근무표'},
      {at: 3, scale: 2.0, x: 0, y: 120, label: '날짜와 근무 코드'},
      {at: 7, scale: 1.65, x: -320, y: 120, label: '구조화 후보'},
      {at: 10, scale: 1.1, x: 0, y: 0, label: 'Calendar로 이동'},
    ],
    highlight: {x: 220, y: 470, w: 1160, h: 170},
  },
  {
    id: 10,
    kicker: 'Chapter 4',
    title: 'AI 일자리 데이터는 Excel 분석과 차트로 설득합니다',
    asset: 'gpt-medical-data.png',
    fit: 'cover',
    why: '데이터는 차트와 해석으로 바뀌어야 설득됩니다.',
    order: ['CSV 확인', 'Excel 정리', '차트/인사이트'],
    result: '의료 현장 변화 메시지를 숫자로 설명합니다.',
    script: '공개 자료를 CSV로 확인하고 Excel에서 정리한 뒤 차트와 인사이트로 바꿉니다.',
    cta: '표를 차트와 메시지로 바꿉니다.',
    focus: [
      {at: 0, scale: 1.04, x: 0, y: 0, label: '분석 전체'},
      {at: 3, scale: 1.2, x: 350, y: 0, label: '원천 데이터'},
      {at: 6, scale: 1.23, x: 0, y: 30, label: 'Excel 정리'},
      {at: 9, scale: 1.22, x: -380, y: 0, label: '차트와 인사이트'},
    ],
    highlight: {x: 1060, y: 160, w: 440, h: 390},
  },
  {
    id: 11,
    kicker: 'Chapter 5',
    title: '환자 안내문은 3문장과 3장 카드뉴스로 바꿉니다',
    cards: ['preview-cardnews-01.png', 'preview-cardnews-02.png', 'preview-cardnews-03.png'],
    why: '긴 안내문은 바로 행동할 수 있는 짧은 메시지가 필요합니다.',
    order: ['문서 읽기', '핵심 3문장', '카드뉴스 3장'],
    result: '검토와 배포가 쉬운 시각 자료가 됩니다.',
    script: '긴 환자 안내문은 핵심을 3문장으로 줄인 뒤 카드뉴스 3장으로 나누면 배포하기 쉬워집니다.',
    cta: '긴 문서를 환자가 이해하는 카드로 바꿉니다.',
    focus: [
      {at: 0, scale: 1.02, x: 0, y: 0, label: '카드 3장'},
      {at: 3, scale: 1.2, x: 360, y: 0, label: '카드 1'},
      {at: 6, scale: 1.2, x: 0, y: 0, label: '카드 2'},
      {at: 9, scale: 1.2, x: -360, y: 0, label: '카드 3'},
    ],
    highlight: {x: 1160, y: 190, w: 280, h: 480},
  },
  {
    id: 12,
    kicker: 'Chapter 6',
    title: '해외 의료 AI 논문은 비교표와 강의자료로 확장합니다',
    asset: 'gpt-papers-to-ppt.png',
    fit: 'cover',
    why: 'PDF 읽기에서 끝내지 않고 수업 산출물로 바꿉니다.',
    order: ['PDF 읽기', '비교 Excel', 'PPT/인포그래픽'],
    result: '논문 기반 강의 준비 시간을 줄입니다.',
    script: '논문을 비교표와 학습 노트, 강의 PPT와 인포그래픽 초안으로 확장할 수 있습니다.',
    cta: '논문을 강의 준비물 묶음으로 바꿉니다.',
    focus: [
      {at: 0, scale: 1.04, x: 0, y: 0, label: '논문 워크플로우'},
      {at: 3, scale: 1.2, x: 380, y: 0, label: 'PDF 읽기'},
      {at: 6, scale: 1.22, x: 0, y: 0, label: '비교표'},
      {at: 9, scale: 1.2, x: -380, y: 0, label: '강의자료'},
    ],
    highlight: {x: 770, y: 170, w: 520, h: 390},
  },
  {
    id: 13,
    kicker: '프롬프트 공식',
    title: 'Codex에게 맡길 때는 다섯 칸만 채우면 됩니다',
    asset: 'gpt-prompt-formula.png',
    fit: 'cover',
    why: '좋은 요청은 빠진 칸이 없는 요청입니다.',
    order: ['자료', '작업', '산출물', '제약', '검토'],
    result: '자기 업무에 바로 복제할 수 있습니다.',
    script: '자료, 작업, 산출물, 제약, 검토라는 다섯 칸이 빠지지 않으면 됩니다.',
    cta: '긴 프롬프트보다 빠진 칸 없는 프롬프트를 만듭니다.',
    focus: [
      {at: 0, scale: 1.04, x: 0, y: 0, label: '다섯 칸 전체'},
      {at: 3, scale: 1.25, x: 430, y: 50, label: '자료'},
      {at: 5, scale: 1.25, x: 210, y: 45, label: '작업'},
      {at: 7, scale: 1.25, x: -10, y: 45, label: '산출물'},
      {at: 9, scale: 1.25, x: -430, y: 45, label: '검토'},
    ],
    highlight: {x: 540, y: 120, w: 840, h: 430},
  },
  {
    id: 14,
    kicker: '마무리 CTA',
    title: '오늘 한 가지 업무를 Codex에게 파일로 맡겨보세요',
    asset: 'cta-start-codex.svg',
    fit: 'contain',
    why: '큰 자동화보다 작은 성공이 먼저입니다.',
    order: ['자료 하나 선택', '산출물 지정', '결과 파일 열기'],
    result: '잘 된 프롬프트를 다음 업무의 출발점으로 씁니다.',
    script: '마지막 CTA입니다. 오늘 한 가지 업무만 고르고 결과 파일을 열어 검토하세요.',
    cta: '지금 파일 하나를 고르세요.',
    focus: [
      {at: 0, scale: 1.02, x: 0, y: 0, label: 'CTA 전체'},
      {at: 3, scale: 1.18, x: 190, y: 20, label: '오늘 한 가지 업무'},
      {at: 6, scale: 1.22, x: 90, y: -40, label: 'Codex에게 맡기기'},
      {at: 9, scale: 1.18, x: -150, y: -110, label: '파일 열어 검토'},
      {at: 11, scale: 1.02, x: 0, y: 0, label: '최종 CTA'},
    ],
    highlight: {x: 320, y: 350, w: 980, h: 125},
  },
];

export const downloads = [
  {
    label: 'Codex 실습 키트 ZIP',
    description: 'HTML 가이드, 샘플 자료, 프롬프트가 포함된 실습 패키지',
    href: '/downloads/codex-practice-kit.zip',
    type: 'ZIP',
    size: 381769,
  },
  {
    label: '강의록 PPT',
    description: 'Remotion 영상의 원본 강의 슬라이드',
    href: '/downloads/codex-lecture-notes.pptx',
    type: 'PPTX',
    size: 12600940,
  },
  {
    label: '근무표 이미지',
    description: 'Google Calendar 실습용 2026년 3월 간호직원근무표',
    href: '/downloads/2603_schudle_test.jpg',
    type: 'JPG',
    size: 61174,
  },
  {
    label: '근무표 실습 ZIP',
    description: '근무표 이미지와 산출물 묶음',
    href: '/downloads/2603_schudle_test.zip',
    type: 'ZIP',
    size: 12665268,
  },
  {
    label: 'AI 의료 일자리 Excel',
    description: 'Chapter 4 데이터 분석 실습용 Excel',
    href: '/downloads/ai_medical_jobs_change_data.xlsx',
    type: 'XLSX',
    size: 11027,
  },
  {
    label: 'AI 의료 일자리 CSV',
    description: 'Excel 분석 전 원본 데이터',
    href: '/downloads/ai_medical_jobs_change_data.csv',
    type: 'CSV',
    size: 924,
  },
  {
    label: '위내시경 환자 안내문 DOCX',
    description: '카드뉴스 변환 실습용 문서',
    href: '/downloads/upper_endoscopy_patient_notice.docx',
    type: 'DOCX',
    size: 37126,
  },
  {
    label: '위내시경 환자 안내문 MD',
    description: '문서 내용을 확인하기 쉬운 Markdown 버전',
    href: '/downloads/upper_endoscopy_patient_notice.md',
    type: 'MD',
    size: 979,
  },
  {
    label: '해외 의료 AI 비교 Excel',
    description: 'Chapter 6 논문 비교 결과 예시',
    href: '/downloads/overseas_medical_ai_adoption_summary.xlsx',
    type: 'XLSX',
    size: 5650,
  },
  {
    label: '논문 학습 노트',
    description: 'PDF 논문을 학습 노트로 정리한 예제',
    href: '/downloads/two_paper_notes.md',
    type: 'MD',
    size: 1867,
  },
  {
    label: 'Remotion 제작 프롬프트',
    description: '슬라이드별 스크립트와 애니메이션 지시문',
    href: '/downloads/remotion_animation_script_prompt.md',
    type: 'MD',
    size: 10319,
  },
];
